services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sportTN-mssql
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Ng26072005.
    volumes:
      - mssql_data:/var/opt/mssql


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_dev
    ports:
      - "5672:5672"   # Cổng kết nối
      - "15672:15672" # Cổng vào giao diện Web để học trực quan
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always

  redis:
    image: redis:7-alpine
    container_name: sportTN-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    command: redis-server --appendonly yes

volumes:
  mssql_data:
  rabbitmq_data:
  redis_data: